name: Build

on:
  push:

jobs:

  unit_tests:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2.4.0
        with:
          java_version: 1.8

      - name: Unit tests
        run: ./gradlew test
